# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AGH_Mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AGH_Mobile
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Fuzi'
  pod 'AlamofireObjectMapper'
  pod 'Charts'
  pod 'TFHpple'

end
